dataset_repo: "Aratako/Japanese-RP-Bench-testdata-SFW"
dataset_split: "train"
target_model_name: "${MODEL}"
target_inference_method: "openai_compatible_api"
user_model_name: "${MODEL}"
user_inference_method: "openai_compatible_api"
judge_model_names:
  - "Llama-3.1-Tulu-3-405B-FP8-Dynamic"
judge_inference_methods:
  - "openai_compatible_api"
evaluation_prompt_file: "./prompts/eval_prompt_SFW.txt"
max_turns: 10
cache_dir: "./.cache"
tensor_parallel_size: 2